const PARKS = [
  {
    id: 'weaverville-joss-house',
    name: 'Weaverville Joss House SHP',
    city: 'Weaverville',
    region: 'Shasta/Trinity',
    lat: 40.7308,
    lon: -122.9428,
    camping: false,
    campsites: 0,
    trailCount: 2,
    topHike: { name: 'Weaver Basin Trail (nearby Trinity Alps)', length: 'varies' },
    allTrailsRating: null,
    allTrailsUrl: 'https://www.alltrails.com/explore/parks/us/california/weaverville-joss-house-state-historic-park',
    parksUrl: 'https://www.parks.ca.gov/?page_id=457',
    cycling: 'Trinity Alps cycling routes nearby',
    scuba: null,
    plannedDate: 'June 2026',
    tripId: 'road-trip-3',
    notes: 'Tours Thu–Sun 10am–5pm only. No trails in park itself. Oldest Chinese temple in CA still in continuous use (built 1874).',
    warning: null,
  },
  {
    id: 'shasta-shp',
    name: 'Shasta SHP',
    city: 'Shasta (near Redding)',
    region: 'Shasta/Redding',
    lat: 40.6032,
    lon: -122.4832,
    camping: false,
    campsites: 0,
    trailCount: 1,
    topHike: { name: 'Shasta State Historic Park Trail', length: '0.6 mi' },
    allTrailsRating: 'Easy',
    allTrailsUrl: 'https://www.alltrails.com/parks/us/california/shasta-state-historic-park',
    parksUrl: 'https://www.parks.ca.gov/?page_id=456',
    cycling: 'Sacramento River Trail in Redding (5 mi paved)',
    scuba: null,
    plannedDate: 'June 2026',
    tripId: 'road-trip-3',
    notes: '1850s gold-rush boomtown ruins with gallows still standing. Closed Tue–Wed.',
    warning: null,
  },
  {
    id: 'william-b-ide-adobe',
    name: 'William B. Ide Adobe SHP',
    city: 'Red Bluff',
    region: 'Shasta/Redding',
    lat: 40.2046,
    lon: -122.2360,
    camping: false,
    campsites: 0,
    trailCount: 2,
    topHike: { name: 'Riverside hillside trail', length: '~0.5 mi' },
    allTrailsRating: null,
    allTrailsUrl: null,
    parksUrl: 'https://www.parks.ca.gov/?page_id=458',
    cycling: 'Sacramento River access nearby',
    scuba: null,
    plannedDate: 'June 2026',
    tripId: 'road-trip-3',
    notes: "Adobe home of Bear Flag Republic's only president. Small but charming. Limited hours — call ahead.",
    warning: null,
  },
  {
    id: 'bidwell-mansion',
    name: 'Bidwell Mansion SHP',
    city: 'Chico',
    region: 'Gold Country North',
    lat: 39.7285,
    lon: -121.8374,
    camping: false,
    campsites: 0,
    trailCount: null,
    topHike: { name: 'Grounds loop (pre-closure)', length: '~1 mi' },
    allTrailsRating: null,
    allTrailsUrl: null,
    parksUrl: 'https://www.parks.ca.gov/?page_id=460',
    cycling: 'Bidwell Park 35+ miles biking nearby',
    scuba: null,
    plannedDate: 'June 2026',
    tripId: 'road-trip-2',
    notes: 'Guided tours only — Sat/Sun at 11am, 1pm, 3pm. Adjacent Bidwell Park has excellent cycling and hiking.',
    warning: 'CLOSED since December 2024 fire — verify reopening before visiting at parks.ca.gov',
  },
  {
    id: 'malakoff-diggins',
    name: 'Malakoff Diggins SHP',
    city: 'Nevada City',
    region: 'Gold Country North',
    lat: 39.4152,
    lon: -120.8986,
    camping: true,
    campsites: 30,
    trailCount: 20,
    topHike: { name: 'Malakoff Diggins & South Yuba Trail Loop', length: '17.8 mi' },
    allTrailsRating: '4.3★',
    allTrailsUrl: 'https://www.alltrails.com/trail/us/california/malakoff-diggins-park-and-south-yuba-trail-loop',
    parksUrl: 'https://www.parks.ca.gov/?page_id=494',
    cycling: 'South Yuba river cycling routes',
    scuba: null,
    plannedDate: 'July 4th weekend',
    tripId: 'gold-country-loop',
    notes: '26 miles of unpaved road to reach — passable in dry weather. Largest hydraulic gold mine in world. Spectacular landscape. 30 campsites ~$35/night.',
    warning: 'Last 8 miles unpaved — check road conditions after rain',
  },
  {
    id: 'empire-mine',
    name: 'Empire Mine SHP',
    city: 'Grass Valley',
    region: 'Gold Country North',
    lat: 39.2157,
    lon: -121.0682,
    camping: false,
    campsites: 0,
    trailCount: 14,
    topHike: { name: 'Hardrock Trail Loop', length: '2.4 mi' },
    allTrailsRating: '4.5★ (1088 reviews)',
    allTrailsUrl: 'https://www.alltrails.com/parks/us/california/empire-mine-state-historic-park',
    parksUrl: 'https://www.parks.ca.gov/EmpireMine/',
    cycling: 'Mountain biking on 5 MTB trails; 14 miles total trails',
    scuba: null,
    plannedDate: 'July 4th weekend',
    tripId: 'gold-country-loop',
    notes: 'Largest, deepest, oldest gold mine in CA history. 14 miles of trails including 5 MTB routes. Excellent museum. $10/car.',
    warning: null,
  },
  {
    id: 'marshall-gold-discovery',
    name: 'Marshall Gold Discovery SHP',
    city: 'Coloma',
    region: 'Gold Country',
    lat: 38.7968,
    lon: -120.8869,
    camping: false,
    campsites: 0,
    trailCount: 3,
    topHike: { name: 'Gam Saan Trail (Gold Mountain)', length: '2.5 mi' },
    allTrailsRating: '4.4★',
    allTrailsUrl: 'https://www.alltrails.com/parks/us/california/marshall-gold-discovery-state-historic-park',
    parksUrl: 'https://www.parks.ca.gov/marshallgold',
    cycling: 'American River cycling access ($5/bike entry)',
    scuba: null,
    plannedDate: 'July 4th weekend',
    tripId: 'gold-country-loop',
    notes: 'Site of 1848 gold discovery. Gold panning available. 3 trails including new 2022 Gam Saan Trail honoring Chinese miners. Living history on July 4th.',
    warning: null,
  },
  {
    id: 'folsom-powerhouse',
    name: 'Folsom Powerhouse SHP',
    city: 'Folsom',
    region: 'Gold Country',
    lat: 38.6832,
    lon: -121.1519,
    camping: false,
    campsites: 0,
    trailCount: 4,
    topHike: { name: 'Lake Natoma American River Trail', length: '11.5 mi' },
    allTrailsRating: '4.7★ (3478 reviews)',
    allTrailsUrl: 'https://www.alltrails.com/parks/us/california/folsom-powerhouse-state-historic-park',
    parksUrl: 'https://www.parks.ca.gov/?page_id=500',
    cycling: 'American River Bike Trail (32 mi to Sacramento)',
    scuba: null,
    plannedDate: 'July 4th weekend',
    tripId: 'gold-country-loop',
    notes: 'First long-distance hydroelectric transmission site. Tours only on weekends. Connects to famous 32-mile American River Bike Trail.',
    warning: 'Open Saturdays and Sundays only — plan accordingly',
  },
  {
    id: 'state-indian-museum',
    name: 'State Indian Museum SHP',
    city: 'Sacramento',
    region: 'Gold Country',
    lat: 38.5743,
    lon: -121.4882,
    camping: false,
    campsites: 0,
    trailCount: 0,
    topHike: { name: 'American River Parkway (nearby)', length: '23 mi' },
    allTrailsRating: null,
    allTrailsUrl: null,
    parksUrl: 'https://www.parks.ca.gov/?page_id=486',
    cycling: 'American River Parkway Bike Trail (23 mi), 1.9 mi away',
    scuba: null,
    plannedDate: 'July 4th weekend',
    tripId: 'gold-country-loop',
    notes: "Urban museum adjacent to Sutter's Fort. Three themes: Nature, Spirit, Family. Collection includes baskets, redwood canoe, ceremonial regalia. Open daily 10am–5pm.",
    warning: null,
  },
  {
    id: 'indian-grinding-rock',
    name: 'Indian Grinding Rock SHP',
    city: 'Volcano / Pine Grove',
    region: 'Gold Country',
    lat: 38.4274,
    lon: -120.6524,
    camping: true,
    campsites: 23,
    trailCount: 2,
    topHike: { name: 'Indian Grinding Rock South Nature Trail', length: '1.4 mi' },
    allTrailsRating: '4.4★ (162 reviews)',
    allTrailsUrl: 'https://www.alltrails.com/trail/us/california/indian-grinding-rock-south-nature-trail',
    parksUrl: 'https://www.parks.ca.gov/?page_id=553',
    cycling: 'Amador County cycling routes',
    scuba: null,
    plannedDate: 'July 5th',
    tripId: 'gold-country-loop',
    notes: 'Largest collection of bedrock mortars in North America (1,185 holes). Bark house camping. Miwok cultural village. 23 campsites with showers.',
    warning: null,
  },
  {
    id: 'anderson-marsh',
    name: 'Anderson Marsh SHP',
    city: 'Lower Lake',
    region: 'North Bay',
    lat: 38.9388,
    lon: -122.5782,
    camping: false,
    campsites: 0,
    trailCount: 6,
    topHike: { name: 'McVicar Trail', length: '8.0 mi' },
    allTrailsRating: '4.2★ (419 reviews)',
    allTrailsUrl: 'https://www.alltrails.com/parks/us/california/anderson-marsh-state-historic-park',
    parksUrl: 'https://www.parks.ca.gov/?page_id=483',
    cycling: 'Lake County cycling routes',
    scuba: null,
    plannedDate: 'Summer 2026',
    tripId: 'day-trip-f',
    notes: '1,065 acres of tule marsh on Clear Lake. 24 prehistoric Koi sites up to 14,000 years old. Excellent bird watching. Cache Creek Trail (2.1 mi) most popular.',
    warning: null,
  },
  {
    id: 'robert-louis-stevenson',
    name: 'Robert Louis Stevenson SHP',
    city: 'Calistoga',
    region: 'North Bay',
    lat: 38.6636,
    lon: -122.5980,
    camping: false,
    campsites: 0,
    trailCount: 5,
    topHike: { name: 'Mount Saint Helena Trail', length: '10.1 mi' },
    allTrailsRating: '4.6★ (2447 reviews)',
    allTrailsUrl: 'https://www.alltrails.com/trail/us/california/mount-saint-helena-trail--2',
    parksUrl: 'https://www.parks.ca.gov/?page_id=472',
    cycling: 'Napa Valley wine country cycling routes',
    scuba: null,
    plannedDate: 'Spring/Summer 2026',
    tripId: 'day-trip-b',
    notes: 'Strenuous summit hike (2,119 ft gain) — one of the best peaks in the Bay Area. No facilities or water. Free entry. RLS honeymooned here 1880.',
    warning: null,
  },
  {
    id: 'bale-grist-mill',
    name: 'Bale Grist Mill SHP',
    city: 'St. Helena',
    region: 'North Bay',
    lat: 38.5499,
    lon: -122.5258,
    camping: false,
    campsites: 0,
    trailCount: 1,
    topHike: { name: 'Bale Grist Mill History Trail', length: '2.4 mi' },
    allTrailsRating: '4.3★ (345 reviews)',
    allTrailsUrl: 'https://www.alltrails.com/trail/us/california/bale-grist-mill-history-trail',
    parksUrl: 'https://www.parks.ca.gov/?page_id=482',
    cycling: 'Napa Valley Pope Valley cycling loop',
    scuba: null,
    plannedDate: 'Spring/Summer 2026',
    tripId: 'day-trip-b',
    notes: '1846 water-powered grist mill. Trail connects to Bothe-Napa Valley SP (camping nearby). Mill demonstrations on weekends. $8 adults. Sat–Sun 10am–4pm.',
    warning: null,
  },
  {
    id: 'jack-london',
    name: 'Jack London SHP',
    city: 'Glen Ellen',
    region: 'North Bay',
    lat: 38.3580,
    lon: -122.5416,
    camping: false,
    campsites: 0,
    trailCount: 10,
    topHike: { name: 'Mountain–Sonoma Ridge–Coon–Vineyard Loop', length: '9.5 mi' },
    allTrailsRating: '4.7★ (846 reviews)',
    allTrailsUrl: 'https://www.alltrails.com/parks/us/california/jack-london-state-historic-park',
    parksUrl: 'https://www.parks.ca.gov/?page_id=478',
    cycling: 'Mountain biking on 26 miles of trails',
    scuba: null,
    plannedDate: 'Spring 2026',
    tripId: 'day-trip-a',
    notes: '1,400 acres. 26 miles of trails (hiking, MTB, equestrian). Beauty Ranch ruins and cottage. Sonoma Mountain summit (2,400 ft). $10/car. Open 7 days 9am–5pm.',
    warning: null,
  },
  {
    id: 'sonoma-shp',
    name: 'Sonoma SHP',
    city: 'Sonoma',
    region: 'North Bay',
    lat: 38.2921,
    lon: -122.4580,
    camping: false,
    campsites: 0,
    trailCount: 2,
    topHike: { name: 'Sonoma Bike Path', length: '1.5 mi' },
    allTrailsRating: '3.6★',
    allTrailsUrl: 'https://www.alltrails.com/parks/us/california/sonoma-state-historic-park',
    parksUrl: 'https://www.parks.ca.gov/?page_id=479',
    cycling: 'Sonoma Valley cycling routes',
    scuba: null,
    plannedDate: 'Spring 2026',
    tripId: 'day-trip-a',
    notes: 'Mission-era barracks, Bear Flag Republic site on Sonoma Plaza. Multiple historic buildings. Free entry. Combine with Jack London for a great day.',
    warning: null,
  },
  {
    id: 'fort-ross',
    name: 'Fort Ross SHP',
    city: 'Cazadero / Jenner',
    region: 'North Bay',
    lat: 38.5147,
    lon: -123.2452,
    camping: true,
    campsites: 20,
    trailCount: 8,
    topHike: { name: 'Reef Campground–Sandy Cove Coastal Trail', length: '~3 mi' },
    allTrailsRating: '4.4★',
    allTrailsUrl: 'https://www.alltrails.com/parks/us/california/fort-ross-state-historic-park',
    parksUrl: 'https://www.parks.ca.gov/fortross',
    cycling: 'Sonoma Coast Hwy 1 cycling (challenging, spectacular)',
    scuba: 'SS Pomona shipwreck (certified divers); Fort Ross Cove reef (snorkel/dive)',
    plannedDate: 'May/Summer 2026',
    tripId: 'day-trip-d',
    notes: '1812 Russian colonial settlement. 3,396 acres. Reef Campground 20 sites, first-come first-served, $40/night, Apr–Nov only. Scuba: SS Pomona wreck off Fort Ross Cove.',
    warning: null,
  },
  {
    id: 'petaluma-adobe',
    name: 'Petaluma Adobe SHP',
    city: 'Petaluma',
    region: 'North Bay',
    lat: 38.3025,
    lon: -122.6413,
    camping: false,
    campsites: 0,
    trailCount: 1,
    topHike: { name: 'Petaluma Adobe Trail', length: '0.4 mi' },
    allTrailsRating: '4.2★',
    allTrailsUrl: 'https://www.alltrails.com/parks/us/california/petaluma-adobe-state-historic-park',
    parksUrl: 'https://www.parks.ca.gov/?page_id=474',
    cycling: 'Sonoma-Marin Area Rail Trail nearby',
    scuba: null,
    plannedDate: 'Spring 2026',
    tripId: 'day-trip-c',
    notes: "General Vallejo's 1836 rancho headquarters. Historic grounds with prickly pear cactus path to adobe. Wed–Sun 10am–5pm. $3/car.",
    warning: null,
  },
  {
    id: 'olompali',
    name: 'Olompali SHP',
    city: 'Novato',
    region: 'North Bay',
    lat: 38.1080,
    lon: -122.5765,
    camping: false,
    campsites: 0,
    trailCount: 4,
    topHike: { name: 'Olompali Trail', length: '3.0 mi' },
    allTrailsRating: '4.5★ (658 reviews)',
    allTrailsUrl: 'https://www.alltrails.com/trail/us/california/olompali-trail',
    parksUrl: 'https://www.parks.ca.gov/olompali',
    cycling: 'Marin cycling routes / US-101 access',
    scuba: null,
    plannedDate: 'Spring 2026',
    tripId: 'day-trip-c',
    notes: 'Coast Miwok site inhabited 6,000+ years. Grateful Dead lived here 1966–67. Extend to Mt Burdell for 8-mi loop. $8/car. Limited hours — verify before visiting.',
    warning: 'Limited open days — call ahead: (415) 892-3383',
  },
  {
    id: 'benicia-sra',
    name: 'Benicia SRA',
    city: 'Benicia',
    region: 'North Bay',
    lat: 38.0582,
    lon: -122.1483,
    camping: true,
    campsites: 3,
    trailCount: 4,
    topHike: { name: 'Carquinez Strait Trail', length: 'varies' },
    allTrailsRating: '4.5★ (1225 reviews)',
    allTrailsUrl: 'https://www.alltrails.com/parks/us/california/benicia-state-recreation-area',
    parksUrl: 'https://www.parks.ca.gov/?page_id=476',
    cycling: '2-mile paved bike path in park; SF Bay Trail access',
    scuba: null,
    plannedDate: 'Spring 2026',
    tripId: 'day-trip-e',
    notes: "California's 2nd state capital 1853–54. 720 acres of marsh and Carquinez hills. 3 enroute campsites (RV/self-contained only, no tents). SF Bay Trail access.",
    warning: null,
  },
  {
    id: 'railtown-1897',
    name: 'Railtown 1897 SHP',
    city: 'Jamestown',
    region: 'Gold Country South',
    lat: 37.9524,
    lon: -120.4307,
    camping: false,
    campsites: 0,
    trailCount: 0,
    topHike: { name: 'N/A — take the steam train instead', length: 'N/A' },
    allTrailsRating: null,
    allTrailsUrl: null,
    parksUrl: 'https://www.parks.ca.gov/?page_id=491',
    cycling: 'Highway 49 Gold Country cycling',
    scuba: null,
    plannedDate: 'June 2026',
    tripId: 'road-trip-2',
    notes: 'Historic steam railroad — no hiking. "Movie Railroad" appeared in 200+ films. Seasonal steam excursions on weekends! $5 museum / $20 train ride. Check train schedule.',
    warning: null,
  },
  {
    id: 'bodie',
    name: 'Bodie SHP',
    city: 'Bridgeport',
    region: 'Eastern Sierra',
    lat: 38.2090,
    lon: -119.0147,
    camping: false,
    campsites: 0,
    trailCount: 2,
    topHike: { name: 'Bodie Historic Walking Tour', length: '1.4 mi' },
    allTrailsRating: '4.7★ (157 reviews)',
    allTrailsUrl: 'https://www.alltrails.com/trail/us/california/bodie-historic-walking-tour',
    parksUrl: 'https://www.parks.ca.gov/bodie',
    cycling: 'No cycling — remote high-desert ghost town',
    scuba: null,
    plannedDate: 'Labor Day (Aug 29)',
    tripId: 'eastern-sierra',
    notes: 'Best-preserved ghost town in the West. 8,375 ft elevation — bring layers. No services. Last 3 miles unpaved. Download offline maps before visiting.',
    warning: 'OPEN MAY–OCTOBER ONLY — Do not delay this visit!',
  },
  {
    id: 'ca-mining-mineral-museum',
    name: 'California Mining & Mineral Museum',
    city: 'Mariposa',
    region: 'Yosemite Gateway',
    lat: 37.4769,
    lon: -119.9671,
    camping: false,
    campsites: 0,
    trailCount: 0,
    topHike: { name: 'Hite Cove Trail (nearby Merced River)', length: '~9 mi RT' },
    allTrailsRating: null,
    allTrailsUrl: null,
    parksUrl: 'https://www.parks.ca.gov/?page_id=588',
    cycling: 'Merced River cycling routes',
    scuba: null,
    plannedDate: 'Labor Day (Aug 30)',
    tripId: 'eastern-sierra',
    notes: 'World-class mineral collection including massive gold specimens. Thu–Sun only. Winter 10am–4pm / Summer 10am–5pm. $4 adults. Located at Mariposa County Fairgrounds.',
    warning: null,
  },
  {
    id: 'san-juan-bautista',
    name: 'San Juan Bautista SHP',
    city: 'San Juan Bautista',
    region: 'Central Coast',
    lat: 36.8425,
    lon: -121.5353,
    camping: false,
    campsites: 0,
    trailCount: 3,
    topHike: { name: 'San Juan Bautista De Anza Trail', length: '5.2 mi RT' },
    allTrailsRating: '4.6★ (870 reviews)',
    allTrailsUrl: 'https://www.alltrails.com/us/california/san-juan-bautista',
    parksUrl: 'https://parks.ca.gov/?page_id=563',
    cycling: 'Monterey Bay Coastal Trail cycling',
    scuba: null,
    plannedDate: 'May/October 2026',
    tripId: 'central-coast',
    notes: "Only CA mission on its original plaza. Setting of Hitchcock's Vertigo! Great Mexican food in town. Open daily 10am–4:30pm.",
    warning: null,
  },
  {
    id: 'monterey-shp',
    name: 'Monterey SHP',
    city: 'Monterey',
    region: 'Central Coast',
    lat: 36.6002,
    lon: -121.8947,
    camping: false,
    campsites: 0,
    trailCount: 1,
    topHike: { name: 'Path of History (self-guided walk)', length: '2 mi' },
    allTrailsRating: null,
    allTrailsUrl: null,
    parksUrl: 'https://www.parks.ca.gov/?page_id=575',
    cycling: 'Monterey Peninsula Recreational Trail',
    scuba: "Breakwater Cove (beginners/night dives); McAbee Beach; Whaler's Cove at Point Lobos (advanced). Best Sep–Nov. Kelp forest, sea lions, wolf eels.",
    plannedDate: 'May/October 2026',
    tripId: 'central-coast',
    notes: "California's oldest public buildings. Collection of historic adobes in Old Monterey. Walk the Path of History past Custom House and Pacific House. Combine with Cannery Row and Fisherman's Wharf.",
    warning: null,
  },
  {
    id: 'colonel-allensworth',
    name: 'Colonel Allensworth SHP',
    city: 'Earlimart',
    region: 'Central Valley',
    lat: 35.8596,
    lon: -119.3943,
    camping: true,
    campsites: 115,
    trailCount: 4,
    topHike: { name: 'Historic Allensworth Trail', length: '1.4 mi' },
    allTrailsRating: '4.6★',
    allTrailsUrl: 'https://www.alltrails.com/parks/us/california/colonel-allensworth-state-historic-park',
    parksUrl: 'https://parks.ca.gov/allensworth/',
    cycling: 'Bikes allowed on all park trails and roads',
    scuba: null,
    plannedDate: 'Nov 26 (Thanksgiving)',
    tripId: 'socal-mega-trip',
    notes: 'Only CA town founded, financed, and governed by African Americans. Deeply moving historic site. 15 developed + ~100 tent sites. $20–30/night. En-route stop on SoCal trip.',
    warning: 'Avoid in summer — San Joaquin Valley reaches 100°F+',
  },
  {
    id: 'fort-tejon',
    name: 'Fort Tejon SHP',
    city: 'Fort Tejon / Lebec',
    region: 'SoCal Gateway',
    lat: 34.8780,
    lon: -118.8624,
    camping: true,
    campsites: 1,
    trailCount: 1,
    topHike: { name: 'Fort Tejón State Park Trail', length: '0.5 mi' },
    allTrailsRating: '4.5★ (34 reviews)',
    allTrailsUrl: 'https://www.alltrails.com/trail/us/california/fort-tejon-state-park',
    parksUrl: 'https://www.parks.ca.gov/?page_id=585',
    cycling: 'I-5 Tejon Pass cycling challenge nearby',
    scuba: null,
    plannedDate: 'Nov 26 (Thanksgiving)',
    tripId: 'socal-mega-trip',
    notes: '1854 US Army fort. Camel Corps history — camels used here experimentally. Group camping only (1 site, 75 people max, reservations required). Easy I-5 stop heading south.',
    warning: null,
  },
  {
    id: 'antelope-valley-indian-museum',
    name: 'Antelope Valley Indian Museum SHP',
    city: 'Lancaster',
    region: 'Southern CA',
    lat: 34.7297,
    lon: -118.0286,
    camping: false,
    campsites: 0,
    trailCount: 1,
    topHike: { name: 'Nature Trail', length: '0.5 mi' },
    allTrailsRating: null,
    allTrailsUrl: null,
    parksUrl: 'https://www.parks.ca.gov/?page_id=632',
    cycling: 'Antelope Valley Trail (paved multi-use)',
    scuba: null,
    plannedDate: 'Nov 28 (Thanksgiving)',
    tripId: 'socal-mega-trip',
    notes: "Museum built into boulders — extraordinary folk architecture. Mojave Desert setting. $3 adults. Plan your SoCal trip around this park's hours!",
    warning: 'Open SATURDAYS AND SUNDAYS ONLY (11am–4pm) — build trip schedule around this',
  },
  {
    id: 'la-purisima-mission',
    name: 'La Purisima Mission SHP',
    city: 'Lompoc',
    region: 'Southern CA',
    lat: 34.6694,
    lon: -120.4317,
    camping: false,
    campsites: 0,
    trailCount: 15,
    topHike: { name: 'La Purisima Trail', length: '3.0 mi loop' },
    allTrailsRating: '4.5★ (608 reviews)',
    allTrailsUrl: 'https://www.alltrails.com/trail/us/california/la-purisima-trail',
    parksUrl: 'https://www.parks.ca.gov/lapurisimamission',
    cycling: 'Mountain biking allowed on trails; Lompoc Valley cycling',
    scuba: 'Jalama Beach County Park (~15 mi) — cold water kelp diving',
    plannedDate: 'Nov 27 (Thanksgiving)',
    tripId: 'socal-mega-trip',
    notes: 'Most completely restored CA mission. 2,000 acres / 25 miles trails open to hiking AND mountain biking. 9am–5pm daily. One of the most impressive missions in CA.',
    warning: null,
  },
  {
    id: 'el-presidio-santa-barbara',
    name: 'El Presidio de Santa Barbara SHP',
    city: 'Santa Barbara',
    region: 'Southern CA',
    lat: 34.4208,
    lon: -119.6982,
    camping: false,
    campsites: 0,
    trailCount: 0,
    topHike: { name: 'Santa Barbara Waterfront path (nearby)', length: '4 mi' },
    allTrailsRating: null,
    allTrailsUrl: null,
    parksUrl: 'https://www.parks.ca.gov/?page_id=608',
    cycling: 'Santa Barbara Waterfront Bike Path (4 mi)',
    scuba: 'Leadbetter Beach (nearby); Anacapa Island / Channel Islands (12 mi offshore) — world-class kelp forest, garibaldi, sea lions',
    plannedDate: 'Nov 27 (Thanksgiving)',
    tripId: 'socal-mega-trip',
    notes: '1782 Spanish military presidio in downtown SB. Very small (5.75 acres) but architecturally fascinating. Free entry. Channel Islands diving nearby is world-class.',
    warning: null,
  },
  {
    id: 'los-encinos',
    name: 'Los Encinos SHP',
    city: 'Encino / Los Angeles',
    region: 'Southern CA',
    lat: 34.1583,
    lon: -118.5016,
    camping: false,
    campsites: 0,
    trailCount: 1,
    topHike: { name: 'Grounds loop (duck pond)', length: '~0.25 mi' },
    allTrailsRating: null,
    allTrailsUrl: null,
    parksUrl: 'https://www.parks.ca.gov/losencinos/',
    cycling: 'Sepulveda Basin Bike Path (6 mi nearby)',
    scuba: null,
    plannedDate: 'Nov 28 (Thanksgiving)',
    tripId: 'socal-mega-trip',
    notes: '4.7-acre rancho site in Encino with spring-fed pond. de la Ossa Adobe and Garnier Building. Free entry. Wed–Sun 10am–5pm. Hidden gem in the San Fernando Valley.',
    warning: null,
  },
  {
    id: 'will-rogers',
    name: 'Will Rogers SHP',
    city: 'Pacific Palisades / LA',
    region: 'Southern CA',
    lat: 34.0544,
    lon: -118.5230,
    camping: false,
    campsites: 0,
    trailCount: 8,
    topHike: { name: 'Inspiration Point Loop', length: '2.0 mi' },
    allTrailsRating: '4.5★',
    allTrailsUrl: 'https://www.alltrails.com/parks/us/california/will-rogers-state-historic-park',
    parksUrl: 'https://www.parks.ca.gov/?page_id=626',
    cycling: 'Backbone Trail (70 mi MTB/hiking); PCH cycling',
    scuba: 'Will Rogers State Beach (nearby); Leo Carrillo Beach (~15 mi north)',
    plannedDate: 'Nov 28 (Thanksgiving)',
    tripId: 'socal-mega-trip',
    notes: 'Former home of humorist Will Rogers. Inspiration Point has panoramic LA and ocean views. Connects to 70-mile Backbone Trail. Grounds open 8am–sunset.',
    warning: 'Ranch house and stables DESTROYED in Jan 2025 Palisades Wildfire. Park reopened Nov 2025 with limited access — verify current status before visiting',
  },
  {
    id: 'california-citrus',
    name: 'California Citrus SHP',
    city: 'Riverside',
    region: 'Southern CA',
    lat: 33.9717,
    lon: -117.3719,
    camping: false,
    campsites: 0,
    trailCount: 5,
    topHike: { name: 'Citrus Interpretive Trail', length: '1.4 mi' },
    allTrailsRating: '4.7★ (272 reviews)',
    allTrailsUrl: 'https://www.alltrails.com/trail/us/california/citrus-interpretive-trail',
    parksUrl: 'https://www.parks.ca.gov/?page_id=649',
    cycling: 'Santa Ana River Trail (30+ mi paved)',
    scuba: null,
    plannedDate: 'Nov 29 (Thanksgiving)',
    tripId: 'socal-mega-trip',
    notes: 'Living heritage citrus grove with 75+ varietals — you can sample fruit while walking! Visitor Center Fri–Sun 10am–4pm. Park daily 8am–5pm. 15 mph bike limit.',
    warning: null,
  },
];

const TRIPS = [
  {
    id: 'day-trip-a',
    name: 'Sonoma Valley Loop',
    type: 'Day Trip',
    subtitle: 'Jack London + Sonoma',
    duration: '1 day',
    parkIds: ['jack-london', 'sonoma-shp'],
    totalMiles: 60,
    suggestedDates: 'Any Saturday, Spring/Summer 2026',
    holidayTag: null,
    description: "A perfect Wine Country day combining the wild Beauty Ranch of America's most adventurous author with California's historic birthplace site at Sonoma Plaza. Both parks are within 15 minutes of each other.",
    highlight: "Jack London's Wolf House ruins and the sweeping Sonoma Mountain views",
    itinerary: [
      {
        day: 'Day 1',
        items: [
          { time: '9:00 AM', location: 'Depart Santa Rosa', description: 'Head south on Hwy 12 toward Glen Ellen' },
          { time: '9:30 AM', location: 'Jack London SHP', description: '2 hrs. Hike Beauty Ranch trails, see the Wolf House ruins and cottage museum.' },
          { time: '12:00 PM', location: 'Lunch in Sonoma', description: 'Sonoma Plaza has excellent restaurants and cafes' },
          { time: '1:30 PM', location: 'Sonoma SHP', description: '1–1.5 hrs. Mission San Francisco Solano, Bear Flag Republic barracks, historic plaza.' },
          { time: '3:00 PM', location: 'Return to Santa Rosa', description: '~45 min drive north' },
        ],
      },
    ],
    accommodations: null,
    warnings: [],
  },
  {
    id: 'day-trip-b',
    name: 'Napa Valley History Loop',
    type: 'Day Trip',
    subtitle: 'Bale Grist Mill + Robert Louis Stevenson',
    duration: '1 day',
    parkIds: ['bale-grist-mill', 'robert-louis-stevenson'],
    totalMiles: 90,
    suggestedDates: 'Any Saturday, Spring/Summer 2026',
    holidayTag: null,
    description: 'Wind through Napa Valley wine country to visit an 1846 working water-powered mill and the volcanic slopes where Robert Louis Stevenson honeymooned in 1880. The Mount St. Helena summit hike offers one of the finest panoramas in Northern California.',
    highlight: 'Summit views from Mount St. Helena stretching across Napa, Sonoma, and Lake Counties',
    itinerary: [
      {
        day: 'Day 1',
        items: [
          { time: '9:00 AM', location: 'Depart Santa Rosa', description: 'Hwy 12 east to Hwy 29 north toward St. Helena' },
          { time: '9:55 AM', location: 'Bale Grist Mill SHP', description: '1 hr. See the 36-ft water wheel in action (weekend demonstrations). History Trail to Bothe-Napa Valley SP.' },
          { time: '11:15 AM', location: 'Robert Louis Stevenson SHP', description: '15 min drive north. 45 min at monument/trailhead — or tackle the full 10.1 mi summit hike (5–6 hrs for fit hikers).' },
          { time: '12:30 PM', location: 'Lunch in Calistoga', description: 'Downtown Calistoga has great restaurants and famous hot springs' },
          { time: '2:00 PM', location: 'Return to Santa Rosa', description: '~1 hr via Hwy 128/12' },
        ],
      },
    ],
    accommodations: null,
    warnings: [],
  },
  {
    id: 'day-trip-c',
    name: 'South Marin Loop',
    type: 'Day Trip',
    subtitle: 'Petaluma Adobe + Olompali',
    duration: '1 day',
    parkIds: ['petaluma-adobe', 'olompali'],
    totalMiles: 80,
    suggestedDates: 'Any Sunday, Spring/Summer 2026',
    holidayTag: null,
    description: "Explore two landmarks of pre-American California — General Vallejo's massive rancho headquarters in Petaluma and the ancient Coast Miwok village site at Olompali, where 6,000 years of continuous habitation left traces still visible today.",
    highlight: "Olompali's hike through oak woodland to panoramic views — where the Grateful Dead once lived",
    itinerary: [
      {
        day: 'Day 1',
        items: [
          { time: '9:30 AM', location: 'Depart Santa Rosa', description: 'South on Hwy 101' },
          { time: '10:10 AM', location: 'Petaluma Adobe SHP', description: "1 hr. General Vallejo's 1836 rancho adobe. Prickly pear cactus pathway." },
          { time: '11:30 AM', location: 'Drive to Novato', description: '~20 min south on Hwy 101' },
          { time: '12:00 PM', location: 'Olompali SHP', description: '1–1.5 hrs. Miwok village site, Olompali Trail (3 mi). Can extend to Mt Burdell for 8-mi loop.' },
          { time: '1:30 PM', location: 'Lunch in Novato', description: 'Novato has good dining options' },
          { time: '2:30 PM', location: 'Return to Santa Rosa', description: '~40 min north on Hwy 101' },
        ],
      },
    ],
    accommodations: null,
    warnings: ['Olompali has limited open days — verify hours before visiting: (415) 892-3383'],
  },
  {
    id: 'day-trip-d',
    name: 'Fort Ross Coastal Drive',
    type: 'Day Trip',
    subtitle: 'Fort Ross (+ optional scuba)',
    duration: '1 day',
    parkIds: ['fort-ross'],
    totalMiles: 100,
    suggestedDates: 'Any Saturday, May–September 2026',
    holidayTag: null,
    description: "A scenic coastal drive along the Sonoma coast to California's only Russian colonial fort, set on dramatic bluffs above the Pacific. For divers, the SS Pomona shipwreck and Fort Ross Cove reef are accessible right from the park.",
    highlight: 'The Russian-era stockade and blockhouses perched above the Pacific — and the optional SS Pomona shipwreck dive',
    itinerary: [
      {
        day: 'Day 1',
        items: [
          { time: '9:00 AM', location: 'Depart Santa Rosa', description: 'West on Hwy 116, then south on Hwy 1 (scenic coastal route)' },
          { time: '10:30 AM', location: 'Fort Ross SHP', description: '2 hrs. Russian colonial fort, chapel, visitor center. Optional: sign up for scuba at Fort Ross Cove (SS Pomona wreck for certified divers).' },
          { time: '12:30 PM', location: 'Lunch at Fort Ross or Jenner', description: 'Picnic at the fort or stop at the Jenner Inn for ocean views' },
          { time: '1:30 PM', location: 'Return to Santa Rosa', description: 'Option: scenic Hwy 1 south to Bodega Bay then inland, or retrace Hwy 116' },
        ],
      },
    ],
    accommodations: null,
    warnings: [],
  },
  {
    id: 'day-trip-e',
    name: 'East Bay History Day',
    type: 'Day Trip',
    subtitle: 'Benicia SRA',
    duration: '1 day',
    parkIds: ['benicia-sra'],
    totalMiles: 120,
    suggestedDates: 'Any Saturday, Spring/Fall 2026',
    holidayTag: null,
    description: "Cross the Bay to Benicia, California's second state capital (1853–54), where a beautifully preserved waterfront historic district sits on the Carquinez Strait. The park's 720 acres of marsh and hills are great for a post-history walk.",
    highlight: 'Walking the original State Capitol building and the Carquinez Strait shoreline',
    itinerary: [
      {
        day: 'Day 1',
        items: [
          { time: '9:00 AM', location: 'Depart Santa Rosa', description: 'Hwy 101 south, I-80 east toward Vallejo' },
          { time: '10:30 AM', location: 'Benicia SRA', description: '1.5–2 hrs. Carquinez Strait trail, waterfront walk. California State Capitol building (Fri–Sun 10am–5pm).' },
          { time: '12:30 PM', location: 'Lunch in Benicia', description: 'Charming downtown waterfront with good restaurants' },
          { time: '2:00 PM', location: 'Return to Santa Rosa', description: '~1.5 hrs north via I-80/Hwy 101' },
        ],
      },
    ],
    accommodations: null,
    warnings: [],
  },
  {
    id: 'day-trip-f',
    name: 'Lake County Loop',
    type: 'Day Trip',
    subtitle: 'Anderson Marsh',
    duration: '1 day',
    parkIds: ['anderson-marsh'],
    totalMiles: 150,
    suggestedDates: 'Any Saturday, Spring/Fall 2026',
    holidayTag: null,
    description: "Head north to Clear Lake to explore Anderson Marsh, one of North America's oldest continuously inhabited sites, where 14,000 years of Koi Nation history meets a spectacular tule marsh bird sanctuary.",
    highlight: 'Best bird watching in the North Bay — herons, egrets, and osprey over the tule marsh',
    itinerary: [
      {
        day: 'Day 1',
        items: [
          { time: '9:00 AM', location: 'Depart Santa Rosa', description: 'Hwy 101 north to Hwy 20 east toward Clear Lake' },
          { time: '10:30 AM', location: 'Anderson Marsh SHP', description: '1.5–2 hrs. Wetlands trails, Cache Creek Trail (2.1 mi) or McVicar Trail (8 mi). 19th century Ranch complex tour.' },
          { time: '12:30 PM', location: 'Lunch in Lakeport or Clearlake', description: 'Clear Lake area has local dining' },
          { time: '1:30 PM', location: 'Return to Santa Rosa', description: '~1.5 hrs south via Hwy 101' },
        ],
      },
    ],
    accommodations: null,
    warnings: [],
  },
  {
    id: 'gold-country-loop',
    name: 'Gold Country North Loop',
    type: 'Road Trip',
    subtitle: '6 parks in 3 days — 4th of July',
    duration: '3 days',
    parkIds: ['empire-mine', 'malakoff-diggins', 'state-indian-museum', 'folsom-powerhouse', 'marshall-gold-discovery', 'indian-grinding-rock'],
    totalMiles: 450,
    suggestedDates: 'July 3–5, 2026 (4th of July Weekend)',
    holidayTag: '4th of July',
    description: 'A patriotic Gold Rush history loop through the Sierra Nevada foothills. Three days, six parks, covering the arc from Sacramento\'s state museum through Nevada City\'s hydraulic mining moonscape to the very spot where gold was discovered in 1848.',
    highlight: 'Marshall Gold Discovery SHP on July 4th — living history programs at the site of the discovery that changed California forever',
    itinerary: [
      {
        day: 'Day 1 — Friday, Jul 3',
        items: [
          { time: '8:00 AM', location: 'Depart Santa Rosa', description: 'Hwy 101 → I-80 east toward Sacramento' },
          { time: '11:00 AM', location: 'Empire Mine SHP (Grass Valley)', description: '~3 hrs drive. 2 hrs. Largest gold mine in CA history. Hardrock Trail Loop (2.4 mi). Excellent museum. $10/car.' },
          { time: '1:30 PM', location: 'Lunch in Grass Valley', description: '' },
          { time: '2:30 PM', location: 'Malakoff Diggins SHP (North Bloomfield)', description: '~35 min from Grass Valley (8 mi unpaved at end). 2 hrs. Largest hydraulic gold mine in world — spectacular landscape.' },
          { time: '5:00 PM', location: 'Check into hotel in Nevada City or Grass Valley', description: 'Nevada City has excellent Gold Rush-era B&Bs and restaurants' },
        ],
      },
      {
        day: 'Day 2 — Saturday, Jul 4',
        items: [
          { time: '8:30 AM', location: 'Depart Nevada City', description: 'I-80 west to Sacramento (~1 hr)' },
          { time: '9:30 AM', location: 'State Indian Museum SHP (Sacramento)', description: "1 hr. Open daily 10am–5pm. Adjacent to Sutter's Fort." },
          { time: '11:00 AM', location: 'Folsom Powerhouse SHP (Folsom)', description: '~25 min. First hydroelectric long-distance transmission. WEEKEND ONLY tours.' },
          { time: '12:30 PM', location: 'Lunch in Folsom', description: '' },
          { time: '2:00 PM', location: 'Marshall Gold Discovery SHP (Coloma)', description: '~35 min. 1.5–2 hrs. Where gold was discovered Jan 24, 1848. July 4th living history programs!' },
          { time: '5:00 PM', location: 'Hotel in Placerville or Auburn', description: 'Watch fireworks in Coloma, Nevada City, or Placerville' },
        ],
      },
      {
        day: 'Day 3 — Sunday, Jul 5',
        items: [
          { time: '8:30 AM', location: 'Depart Placerville', description: 'Hwy 49 south ~45 min to Pine Grove' },
          { time: '9:30 AM', location: 'Indian Grinding Rock SHP (Volcano)', description: '1.5 hrs. 1,185 bedrock mortar cups. Bark house camping. Miwok village.' },
          { time: '11:30 AM', location: 'Lunch in Jackson or Sutter Creek', description: 'Gold Country charm' },
          { time: '1:00 PM', location: 'Return to Santa Rosa', description: 'Hwy 88 west → ~3 hrs home' },
        ],
      },
    ],
    accommodations: 'Nevada City or Grass Valley (Night 1); Placerville or Auburn (Night 2)',
    warnings: [
      'Malakoff Diggins: last 8 miles unpaved — passable in dry summer, confirm after rain',
      'Folsom Powerhouse open weekends only — Saturday July 4th works perfectly',
    ],
  },
  {
    id: 'road-trip-2',
    name: 'Gold Country South + Mother Lode',
    type: 'Road Trip',
    subtitle: 'Railtown 1897 + Bidwell Mansion',
    duration: '2 days',
    parkIds: ['railtown-1897', 'bidwell-mansion'],
    totalMiles: 400,
    suggestedDates: 'Any weekend, June–September 2026',
    holidayTag: null,
    description: "Two parks that don't cluster easily with others — a weekend loop pairing the historic steam railroad roundhouse in Jamestown with the Victorian mansion of Chico's founder, John Bidwell.",
    highlight: 'Riding behind a real steam locomotive at Railtown 1897 — the "Movie Railroad" of Hollywood\'s Golden Age',
    itinerary: [
      {
        day: 'Day 1 — Saturday',
        items: [
          { time: '7:30 AM', location: 'Depart Santa Rosa', description: 'Hwy 12 east to I-5 or Hwy 99 south' },
          { time: '11:00 AM', location: 'Railtown 1897 SHP (Jamestown)', description: '~3.5 hrs. 2 hrs. Historic steam roundhouse. Check weekend steam train excursion schedule! $5 museum.' },
          { time: '1:30 PM', location: 'Lunch in Sonora or Jamestown', description: 'Charming Gold Country towns' },
          { time: '3:00 PM', location: 'Hotel in Sonora', description: 'Gold Rush-era downtown, excellent dinner options' },
        ],
      },
      {
        day: 'Day 2 — Sunday',
        items: [
          { time: '8:00 AM', location: 'Depart Sonora', description: 'Hwy 108 west → Hwy 99 north (~2.5 hrs)' },
          { time: '11:00 AM', location: 'Bidwell Mansion SHP (Chico)', description: "VERIFY OPEN — closed since Dec 2024 fire. If open: guided tour (11am, 1pm, 3pm). Victorian mansion of Chico's founder." },
          { time: '1:00 PM', location: 'Lunch in Chico', description: 'Explore Chico State campus area' },
          { time: '2:30 PM', location: 'Return to Santa Rosa', description: 'Hwy 99 south to I-5/I-80 → ~3 hrs' },
        ],
      },
    ],
    accommodations: 'Sonora, CA (Night 1)',
    warnings: ['Bidwell Mansion closed since Dec 2024 fire — check parks.ca.gov for reopening before booking this trip'],
  },
  {
    id: 'road-trip-3',
    name: 'Shasta/Redding + Red Bluff',
    type: 'Road Trip',
    subtitle: 'Weaverville + Shasta + William B. Ide Adobe',
    duration: '2 days',
    parkIds: ['weaverville-joss-house', 'shasta-shp', 'william-b-ide-adobe'],
    totalMiles: 480,
    suggestedDates: 'June or early July 2026',
    holidayTag: null,
    description: 'Head north to the upper Sacramento Valley for three very different historic parks — the half-ruined boomtown of Shasta City, the extraordinary Chinese temple of Weaverville, and the riverside adobe of the Bear Flag Republic\'s only president.',
    highlight: 'Weaverville Joss House — a Taoist temple in continuous use since 1874, hidden in the Trinity Alps foothills',
    itinerary: [
      {
        day: 'Day 1 — Saturday',
        items: [
          { time: '7:00 AM', location: 'Depart Santa Rosa', description: 'Hwy 101 north → US-101 → I-5 north' },
          { time: '10:00 AM', location: 'Shasta SHP (6 mi west of Redding)', description: '~3 hrs drive. 2 hrs. Gold Rush boomtown ruins. Gallows still standing. Excellent museum. Closed Tue–Wed.' },
          { time: '12:30 PM', location: 'Lunch in Redding', description: '' },
          { time: '2:00 PM', location: 'Weaverville Joss House SHP', description: '~45 min west on Hwy 299. 1.5 hrs. Guided tour of the 1874 Taoist temple. Tours on the hour.' },
          { time: '4:30 PM', location: 'Return to Redding', description: '~45 min east' },
          { time: '5:30 PM', location: 'Hotel in Redding', description: 'Affordable chain hotels; gateway to Northern CA parks' },
        ],
      },
      {
        day: 'Day 2 — Sunday',
        items: [
          { time: '8:30 AM', location: 'Depart Redding', description: 'I-5 south ~35 min' },
          { time: '9:15 AM', location: 'William B. Ide Adobe SHP (Red Bluff)', description: '1 hr. Adobe home of the only president of the California Republic. Riverside picnic area.' },
          { time: '10:30 AM', location: 'Return to Santa Rosa', description: 'I-5 south → ~2.5 hrs home' },
        ],
      },
    ],
    accommodations: 'Redding, CA (Night 1)',
    warnings: [
      'Weaverville Joss House tours Thu–Sun only',
      'Shasta SHP closed Tue–Wed — check open days',
    ],
  },
  {
    id: 'eastern-sierra',
    name: 'Eastern Sierra Adventure',
    type: 'Road Trip',
    subtitle: 'Bodie + CA Mining Museum (Labor Day)',
    duration: '3 days',
    parkIds: ['bodie', 'ca-mining-mineral-museum'],
    totalMiles: 700,
    suggestedDates: 'August 29–September 1, 2026 (Labor Day Weekend)',
    holidayTag: 'Labor Day',
    description: "A spectacular Eastern Sierra road trip to America's most authentic gold-rush ghost town, perched at 8,375 feet above sea level, followed by the world-class mineral collection in Mariposa at the gateway to Yosemite.",
    highlight: 'Bodie at golden hour — 200 abandoned buildings perfectly preserved by state law in a state of "arrested decay"',
    itinerary: [
      {
        day: 'Day 1 — Saturday, Aug 29',
        items: [
          { time: '7:00 AM', location: 'Depart Santa Rosa', description: 'US-101 south → I-580 → I-205 → US-395 north via Bridgeport' },
          { time: '12:30 PM', location: 'Lunch in Bridgeport or Lee Vining', description: 'Last services before Bodie' },
          { time: '2:00 PM', location: 'Bodie SHP', description: '~5.5 hrs drive. Allow 2–3 hrs minimum — this park deserves time. 200 abandoned buildings, no services. Last 3 mi unpaved.' },
          { time: '5:30 PM', location: 'Hotel in Bridgeport or Lee Vining', description: 'Small but charming gateway towns; book ahead for Labor Day' },
        ],
      },
      {
        day: 'Day 2 — Sunday, Aug 30',
        items: [
          { time: '8:00 AM', location: 'Depart Bridgeport', description: 'US-395 south → Hwy 120 west (Tioga Pass, if open) or US-395 south to Hwy 140' },
          { time: '10:30 AM', location: 'CA Mining & Mineral Museum (Mariposa)', description: '~2.5 hrs. 1.5 hrs. World-class mineral and gold specimens. Thu–Sun 10am–5pm. $4 adults.' },
          { time: '12:30 PM', location: 'Lunch in Mariposa', description: 'Gateway to Yosemite — good dining options' },
          { time: '2:00 PM', location: 'Optional: Yosemite Valley', description: '30 min away — worth it if you have time!' },
          { time: '4:00 PM', location: 'Head north/west', description: 'Overnight in Fresno or Mariposa' },
        ],
      },
      {
        day: 'Day 3 — Monday, Sep 1',
        items: [
          { time: 'Morning', location: 'Return to Santa Rosa', description: 'Hwy 99 north → I-5/I-80 or Hwy 120 → ~4–5 hrs home' },
        ],
      },
    ],
    accommodations: 'Bridgeport or Lee Vining (Night 1); Mariposa or Fresno (Night 2)',
    warnings: [
      'Bodie open MAY–OCTOBER ONLY — this is your Labor Day window',
      'Download offline maps — no cell service at Bodie',
      'Tioga Pass (Hwy 120) through Yosemite may be closed — check status',
    ],
  },
  {
    id: 'central-coast',
    name: 'Central Coast Weekend',
    type: 'Road Trip',
    subtitle: 'San Juan Bautista + Monterey',
    duration: '2 days',
    parkIds: ['san-juan-bautista', 'monterey-shp'],
    totalMiles: 350,
    suggestedDates: 'Any weekend, May–November 2026',
    holidayTag: null,
    description: "A weekend on California's iconic Central Coast combining the only mission still on its original plaza — setting of Hitchcock's Vertigo — with Monterey's collection of historic adobes and the world-class diving of Monterey Bay National Marine Sanctuary.",
    highlight: "Cannery Row, the Path of History, and Monterey Bay's kelp forest diving at Breakwater Cove",
    itinerary: [
      {
        day: 'Day 1 — Saturday',
        items: [
          { time: '8:00 AM', location: 'Depart Santa Rosa', description: 'Hwy 101 south through San Francisco and Silicon Valley' },
          { time: '10:30 AM', location: 'San Juan Bautista SHP', description: "~2.5 hrs. 1.5 hrs. Historic mission plaza (location of Hitchcock's Vertigo), old adobe hotel and barracks. Great Mexican lunch in town." },
          { time: '1:00 PM', location: 'Lunch in San Juan Bautista', description: 'El Camino Real-era setting' },
          { time: '2:30 PM', location: 'Drive to Monterey', description: '~45 min west' },
          { time: '3:15 PM', location: 'Monterey SHP', description: '1.5 hrs. Path of History walk past Custom House and Pacific House.' },
          { time: '5:00 PM', location: 'Hotel in Monterey', description: 'Walk Cannery Row; dinner at Fisherman\'s Wharf' },
        ],
      },
      {
        day: 'Day 2 — Sunday',
        items: [
          { time: 'Morning', location: 'Optional: Scuba at Breakwater Cove', description: 'World-class diving — kelp forest, sea lions, nudibranchs. Contact Aquarius Divers or Bamboo Reef for guided dives.' },
          { time: 'Morning', location: 'Optional: 17-Mile Drive or Carmel', description: 'World-famous scenic drive or charming coastal village' },
          { time: 'Noon', location: 'Depart Monterey', description: '' },
          { time: '3:00 PM', location: 'Arrive Santa Rosa', description: 'Hwy 101 north' },
        ],
      },
    ],
    accommodations: 'Monterey, CA (Night 1)',
    warnings: [],
  },
  {
    id: 'socal-mega-trip',
    name: 'Southern California Grand Tour',
    type: 'Road Trip',
    subtitle: '8 parks — Thanksgiving Weekend',
    duration: '4 days',
    parkIds: ['colonel-allensworth', 'fort-tejon', 'la-purisima-mission', 'el-presidio-santa-barbara', 'antelope-valley-indian-museum', 'los-encinos', 'will-rogers', 'california-citrus'],
    totalMiles: 1100,
    suggestedDates: 'November 26–29, 2026 (Thanksgiving Weekend)',
    holidayTag: 'Thanksgiving',
    description: 'The big one — a Thanksgiving sweep of all Southern California and Central Valley parks. Late November is ideal: mild weather (65–75°F), low park crowds, and no summer heat in the Antelope Valley or Riverside. Eight parks in four days.',
    highlight: 'Colonel Allensworth — the only California town founded, financed, and governed by African Americans — a deeply moving and undervisited historic site',
    itinerary: [
      {
        day: 'Day 1 — Thursday, Nov 26 (Thanksgiving)',
        items: [
          { time: '7:00 AM', location: 'Depart Santa Rosa', description: 'I-5 south — long drive day' },
          { time: '11:00 AM', location: 'Colonel Allensworth SHP (Earlimart)', description: '~5.5 hrs. 2 hrs. Deeply moving history. 115 campsites if staying overnight.' },
          { time: '1:30 PM', location: 'Continue south', description: 'I-5 south toward Fort Tejon' },
          { time: '2:30 PM', location: 'Fort Tejon SHP (Lebec)', description: '1 hr. 1854 Army fort. Easy I-5 stop. Camel Corps history.' },
          { time: '4:00 PM', location: 'Hotel in Santa Clarita or Burbank', description: 'LA suburban hotels are good value' },
        ],
      },
      {
        day: 'Day 2 — Friday, Nov 27',
        items: [
          { time: '8:00 AM', location: 'Depart hotel', description: 'Drive toward Lompoc (~1.5 hrs via US-101/Hwy 1)' },
          { time: '9:30 AM', location: 'La Purisima Mission SHP (Lompoc)', description: '2 hrs. Most completely restored mission in CA. 25 miles of trails.' },
          { time: '12:00 PM', location: 'Drive to Santa Barbara', description: '~45 min east on US-101' },
          { time: '1:30 PM', location: 'El Presidio de Santa Barbara SHP', description: '1.5 hrs. 1782 Spanish presidio in downtown SB. Walk the waterfront bike path after.' },
          { time: '3:30 PM', location: 'Drive to LA area', description: '~1.5 hrs east on US-101' },
          { time: '5:00 PM', location: 'Hotel in Santa Monica or Culver City', description: "Good base for the next day's LA parks" },
        ],
      },
      {
        day: 'Day 3 — Saturday, Nov 28',
        items: [
          { time: '9:00 AM', location: 'Will Rogers SHP (Pacific Palisades)', description: '1.5 hrs. Inspiration Point views (2-mi loop). Grounds open 8am. Check ranch access — limited due to 2025 fire.' },
          { time: '11:00 AM', location: 'Drive to Encino', description: '~25 min via I-405' },
          { time: '11:30 AM', location: 'Los Encinos SHP (Encino)', description: '1 hr. Adobe rancho and spring-fed duck pond. Free. Wed–Sun 10am–5pm.' },
          { time: '1:00 PM', location: 'Lunch in Encino or Studio City', description: '' },
          { time: '2:30 PM', location: 'Antelope Valley Indian Museum (Lancaster)', description: '~1 hr via Hwy 14. 1.5 hrs. Museum built INTO boulders. VERIFY open on Sat. $3. 11am–4pm.' },
          { time: '5:30 PM', location: 'Drive to Riverside area', description: '~2 hrs via I-15 south' },
          { time: '7:30 PM', location: 'Hotel in Riverside or Ontario', description: '' },
        ],
      },
      {
        day: 'Day 4 — Sunday, Nov 29',
        items: [
          { time: '9:00 AM', location: 'California Citrus SHP (Riverside)', description: '1.5 hrs. Living citrus grove — sample oranges, kumquats, lemons while you walk. Open 8am–5pm.' },
          { time: '11:00 AM', location: 'Depart for Santa Rosa', description: 'I-15 north → I-5 north → Bay Area → Hwy 101 north' },
          { time: '5:00–6:00 PM', location: 'Arrive Santa Rosa', description: 'All 32 parks complete!' },
        ],
      },
    ],
    accommodations: 'Santa Clarita or Burbank (Night 1); Santa Monica or Culver City (Night 2); Riverside or Ontario (Night 3)',
    warnings: [
      'Will Rogers SHP ranch house destroyed in Jan 2025 Palisades Fire — verify current access',
      'Antelope Valley Indian Museum: Saturday/Sunday ONLY, 11am–4pm — build Day 3 schedule around this',
      'Thanksgiving I-5 southbound traffic is heavy Friday PM — depart Thursday morning',
    ],
  },
];
